### ISSUE TITLE
'PassbookUIServic' access to protected services is denied.

### ISSUE THREAD

**Issue by boardmain** [appcelerator-archive/ti.passbook#3]
hi i have this errors and app chars ( pass is displayed on addpass )

Oct  3 11:45:23 Mac-mini-di-Francesco.local backboardd[30032] <Error>: HID: The 'Passive' connection 'PassbookUIServic' access to protected services is denied.
Oct  3 11:45:23 Mac-mini-di-Francesco.local PassbookUIService[30155] <Warning>: Failed to inherit CoreMedia permissions from 30055: (null)

**Comment by hansemannn** [comment]
You need to specify the correct entitlements, check [this thread](http://stackoverflow.com/questions/27343681/xcode-today-extension-stuck-on-failed-to-inherit-coremedia-permissions-error).
