### ISSUE TITLE
Solution to Viewing a Pass in Wallet (iOS 10+)

### ISSUE THREAD

**Issue by yozef** [appcelerator-archive/ti.passbook#8]
in tiapp.xml:

```
<key>com.apple.developer.pass-type-identifiers</key>
<array>
    <string>YourTeamId.*</string>  // <--- and not: com.pass.domain.coupon as in Entitlements.plist
</array>
```

In addition to placing [Entitlements.plist](https://github.com/appcelerator-archive/ti.passbook/blob/master/ios/example/Basic/Entitlements.plist) in your root project.

**Comment by hansemannn** [comment]
Is that an issue or proposal? :-) If the latter, I'd be happy to merge a PR you make to update the docs, thx!
